apiVersion: v1
kind: Pod
metadata:
  name: mysite-pod
  labels:
    function: app
spec:
  containers:
  - name: django
    image: ghcr.io/frisbeedata/cis-92:milestone-6.2
    ports:
    volumeMounts:
    - name: db
      mountPath: /data:
    - containerPort: 8000
    resources:
      requests:
        cpu: 250m 
        memory: 512Mi
        ephemeral-storage: 10Mi
      limits:
        cpu: 250m 
        memory: 512Mi
        ephemeral-storage: 10Mi
    volumes:
      - name: db
        persistentVolumeClaim:
          claimName: mysite-data
    envFrom:
      - configMapRef:
          name: mysite-config
      - secretRef:
          name: mysite-secret